app:
  name: golang-article-api
  version: 1.0.0

web:
  prefork: false
  port: 5050

log:
  level: 5

database:
  user: postgres
  password: wkwkland
  host: localhost
  port: 5432
  name: golang_article_api
  pool:
    idle: 10
    max: 50
    lifetime: 30
    idletime: 5
