// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jordanmarcelino/go-article-api/internal/config"
	"github.com/jordanmarcelino/go-article-api/internal/controller"
	"github.com/jordanmarcelino/go-article-api/internal/middleware"
	"github.com/jordanmarcelino/go-article-api/internal/repository"
	"github.com/jordanmarcelino/go-article-api/internal/usecase"
)

// Injectors from injector.go:

func InitializedServer() *config.RouteConfig {
	viper := config.NewViper()
	app := config.NewFiber(viper)
	logger := config.NewLogger(viper)
	db := config.NewDatabase(viper, logger)
	validate := config.NewValidator(viper)
	userRepository := repository.NewUserRepository(logger)
	userUseCase := usecase.NewUserUseCase(db, logger, validate, userRepository)
	userController := controller.NewUserController(logger, userUseCase)
	articleRepository := repository.NewArticleRepository(logger)
	articleUseCase := usecase.NewArticleUseCase(db, logger, validate, articleRepository)
	articleController := controller.NewArticleController(logger, articleUseCase)
	tagRepository := repository.NewTagRepository(logger)
	tagUseCase := usecase.NewTagUseCase(db, logger, validate, tagRepository)
	tagController := controller.NewTagController(logger, tagUseCase)
	commentRepository := repository.NewCommentRepository(logger)
	commentUseCase := usecase.NewCommentUseCase(db, logger, validate, commentRepository)
	commentController := controller.NewCommentController(logger, commentUseCase)
	v := middleware.Protected()
	routeConfig := config.NewRouteConfig(app, viper, logger, userController, articleController, tagController, commentController, v)
	return routeConfig
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, usecase.NewUserUseCase, controller.NewUserController)

var articleSet = wire.NewSet(repository.NewArticleRepository, usecase.NewArticleUseCase, controller.NewArticleController)

var tagSet = wire.NewSet(repository.NewTagRepository, usecase.NewTagUseCase, controller.NewTagController)

var commentSet = wire.NewSet(repository.NewCommentRepository, usecase.NewCommentUseCase, controller.NewCommentController)
